# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- release

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'subbupro'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'subbupro_React'
    cliProjectName: 'React'
    cliSources: '.'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

  #Please check the below command npm run test in your local after that 
  # add it here, until then comment it.  
# - task: Npm@1
#   displayName: npm run test
#   inputs:
#     command: custom
#     customCommand: run ci:unit
# - task: Npm@1
#   displayName: npm run cypress
#   inputs:
#     command: custom
#     customCommand: run ci:cypress

- upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop

